### ISSUE TITLE
Post pakai huruf kecil

### ISSUE THREAD

**Issue by yohangdev** [rizkyrmsyah/learn-laravel#7]
https://github.com/rizkyrmsyah/learn-laravel/blob/ec4fc3e4149fba1fb48fb8e7b6a4be6bfcb93fa3/routes/api.php#L33

Harusnya ini pakai huruf kecil `post()` 😁

**Comment by firmanJS** [comment]
ini ada issue dari mas @yohang88 , nanti di perbaiki @rizkyrmsyah hehehe kalo butuh diskusi japri aja :smile:

**Comment by rizkyrmsyah** [comment]
[fix issue](https://github.com/rizkyrmsyah/learn-laravel/commit/07f905f37cf22ca17818a5796241204d3d55317f)
issue nya udah fixed kang @firmanJS and mas @yohang88 👯‍♀️
